name = "bluebush-ai"
main = "cloudflare/bluebush-chat-relay-d1.js"
compatibility_date = "2026-05-18"

[vars]
ALLOWED_ORIGINS = "https://azzamunza.github.io"

[[d1_databases]]
binding = "DB"
database_name = "bluebush-db"
database_id = "e2ac9d81-762e-4565-81d3-27510cb0907d"

[[vectorize]]
binding = "VECTORIZE"
index_name = "bluebush-index"

[ai]
binding = "AI"
